events {
    worker_connections 1024;
}

http {
    upstream server_instances {
            server backend1:8080;
            server backend2:8080;

        }

    server {
        listen 80;

        location / {
            proxy_pass http://server_instances;

            # Добавляет заголовок с ip адресом клиента
            proxy_set_header Host $host;

            # Добавляет IP клиента в цепочку прокси (прокси может быть несколько)
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Добавляет протокол клиента (http или https)
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}